# Generated by Django 6.0.6 on 2026-07-20 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at time of movement (stock-in only).', max_digits=10, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', help_text='PO number, invoice ref, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
