# Generated by Django 6.0.6 on 2026-07-06 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Company', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('tax_id', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='DA — Algerian Dinar', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='InventoryPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_threshold', models.PositiveIntegerField(default=10)),
                ('default_unit', models.CharField(default='pcs', max_length=20)),
                ('valuation_method', models.CharField(choices=[('weighted_average', 'Weighted Average'), ('fifo', 'FIFO'), ('last_purchase', 'Last Purchase Price')], default='weighted_average', max_length=30)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_in_app', models.BooleanField(default=True)),
                ('low_stock_email', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('alert_threshold', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
